version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx*"
      spring-boot:
        patterns:
          - "org.springframework.boot*"
          - "org.springframework.dependency-management*"
      testing:
        patterns:
          - "io.kotest*"
          - "io.mockk*"
          - "org.testcontainers*"
          - "org.wiremock*"
          - "com.icegreen*"
      static-analysis:
        patterns:
          - "io.gitlab.arturbosch.detekt*"
          - "org.jlleitschuh.gradle.ktlint*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
